@baseUrl = http://localhost:5000
@bookId = c0a80121-48aa-48b0-8c0c-927b1f8eac2c

### retrieve all books (synchronously)
GET {{baseUrl}}/api/books/sync HTTP/1.1


### retrieve a book (synchronously)
GET {{baseUrl}}/api/books/sync/{{bookId}} HTTP/1.1

### retrieve all books (asynchronously)
GET {{baseUrl}}/api/books/async HTTP/1.1

### retrieve a book (asynchronously)
GET {{baseUrl}}/api/books/async/{{bookId}} HTTP/1.1