### Books API
###
### These tests can be executed from within Visual Studio Code, provided that the user has 
### already installed the "REST Client" extension. That extension can be installed from this
### link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl = http://localhost:5000
@bookId = c0a80121-48aa-48b0-8c0c-927b1f8eac2c

### retrieve all books (synchronously)
GET {{baseUrl}}/api/books/sync HTTP/1.1

### retrieve a book (synchronously)
GET {{baseUrl}}/api/books/sync/{{bookId}} HTTP/1.1

### retrieve all books (asynchronously)
GET {{baseUrl}}/api/books/async HTTP/1.1

### retrieve a book (asynchronously)
GET {{baseUrl}}/api/books/async/{{bookId}} HTTP/1.1

### create a book (synchronously)
POST {{baseUrl}}/api/books/sync HTTP/1.1
Content-Type: application/json

{
    "title": "A Clash of Kings",
    "description": "The second book in the A Song of Ice and Fire series.",    
    "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
}

### create a book (asynchronously)
POST {{baseUrl}}/api/books/async HTTP/1.1
Content-Type: application/json

{
    "title": "A Storm of Swords",
    "description": "The third book in the A Song of Ice and Fire series.",
    "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
}

### update a book (synchronously)
PUT {{baseUrl}}/api/books/sync/{{bookId}} HTTP/1.1
Content-Type: application/json

{
  "id": "c0a80121-48aa-48b0-8c0c-927b1f8eac2c",
  "title": "A Game of Thrones",
  "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
}

### update a book (asynchronously)
PUT {{baseUrl}}/api/books/async/{{bookId}} HTTP/1.1
Content-Type: application/json

{
  "id": "c0a80121-48aa-48b0-8c0c-927b1f8eac2c",
  "title": "A Game of Thrones",
  "description": "The first book in the A Song of Ice and Fire series.",
  "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
}

### delete a book (synchronously)
DELETE {{baseUrl}}/api/books/sync/{{bookId}} HTTP/1.1

### delete a book (asynchronously)
DELETE {{baseUrl}}/api/books/async/{{bookId}} HTTP/1.1

### add books at bulk
POST {{baseUrl}}/api/books/bulk HTTP/1.1
Content-Type: application/json

[
  {
    "title": "A Clash of Kings",
    "description": "The second book in the A Song of Ice and Fire series.",
    "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
  },
  {
    "title": "A Storm of Swords",
    "description": "The third book in the A Song of Ice and Fire series.",
    "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
  }
]

### update books at bulk
PUT {{baseUrl}}/api/books/bulk HTTP/1.1
Content-Type: application/json

[
  {
    "id": "3e0de5b1-af7c-4dd7-9ad7-b594ede0d80e",
    "title": "A Clash of Kings",
    "description": "[UPDATED] The second book in the A Song of Ice and Fire series.",
    "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
  },
  {
    "id": "62f6d826-22ec-47c3-8a33-2bacfda3f34a",
    "title": "A Storm of Swords",
    "description": "[UPDATED] The third book in the A Song of Ice and Fire series.",
    "authorId": "c0a80121-48aa-48b0-8c0c-927b1f8eac2e"
  }
]

### delete books at bulk
DELETE {{baseUrl}}/api/books/bulk HTTP/1.1
Content-Type: application/json

[
  "3e0de5b1-af7c-4dd7-9ad7-b594ede0d80e",
  "62f6d826-22ec-47c3-8a33-2bacfda3f34a"
]
